fix tsc error TS2339 and TS2322
- Property '_negotiator' does not exist on type 'SfuRoom'.
- Type 'RTCPeerConnection | null' is not assignable to type 'RTCPeerConnection'.