fix tsc error TS2345
- Object literal may only specify known properties, and '_' does not exist in type 'AnnotationsMap<this, never>'.
- see 8 of https://mobx.js.org/observable-state.html#limitations