fix tsc error TS2739 and TS2322
- Type 'never[]' is missing the following properties from type 'IObservableArray<_>'
- Type 'never[]' is not assignable to type 'IObservableArray<_>'