pass npm run lint (#4)
* fix eslint initial error

- "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0.
- "prettier/react" has been merged into "prettier" in eslint-config-prettier 8.0.0.

* add --fix option to eslint

* first eslint --fix

* fix eslint error, use Record<string, never>, Record<string, unknown>

- Don't use `{}` as a type.

* fix eslint error, pass an inline function instead

- React Hook useCallback received a function whose dependencies are unknown.

* fix eslint error and warning

- React Hook useCallback has an unnecessary dependency
- assigned a value but never used

* tmp delete @ts-ignore

* fix tsc error TS2322

- Property 'css' does not exist on type 'DetailedHTMLProps<_>'.

* fix tsc error TS2345

- Object literal may only specify known properties, and '_' does not exist in type 'AnnotationsMap<this, never>'.
- see 8 of https://mobx.js.org/observable-state.html#limitations
- Argument of type 'unknown' is not assignable to parameter of type 'Error'.
- Argument of type '() => React.EffectCallback' is not assignable to parameter of type 'EffectCallback'.

* fix tsc error TS2554

- Expected 0 arguments, but got 1.
- eslint error: no-self-assign

* fix tsc error TS2739 and TS2322

- Type 'never[]' is missing the following properties from type 'IObservableArray<_>'
- Type 'never[]' is not assignable to type 'IObservableArray<_>'

* fix tsc error TS2339 and TS2322

- Property '_negotiator' does not exist on type 'SfuRoom'.
- Type 'RTCPeerConnection | null' is not assignable to type 'RTCPeerConnection'.

* fix tsc error TS2339

- Property 'store' does not exist on type 'Window & typeof globalThis'.